### ISSUE TITLE
Implicit cast compilation error is misleading.

### ISSUE THREAD

**Issue by Nimeshius** [Practical/practical-sa#2] opened 2019-03-13 08:51 UTC
When compiling the following code:
{
   def var1: s32 = 5;
   def var2: u32 = var1;
   //Do something.
}

I get a compilation error along the lines of:
"s32 cast to u32 is not allowed"

This error is misleading as an **explicit** cast is allowed, it is just not allowed implicitly.

**Comment by Shachar** [comment] 2019-03-15 07:33
Thank you for the report. The issue is now fixed in master.

**Closed as completed by Shachar** 2019-03-15 07:33 UTC
Labels: enhancement
